- name: add user simone
  user:
   name: simone
   groups: root

- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFVT2vlHd5KqTEVpSgitGqC/0ThxRUYtUGLs/z99GZHO ansible"

- name: add sudoers file for simone
  copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440
